GET http://localhost:8000/categories

###

POST http://localhost:8000/categories
content-type: application/json

{
    "name": "Эдийн засаг"
}

###
DELETE  http://localhost:8000/categories
###

PUT http://localhost:8000/categories
content-type: application/json
{
    "name": "Нийгэм"
}

###
GET http://localhost:8000/articles
###
POST http://localhost:8000/articles

