GET http://localhost:8000/categories

###

POST http://localhost:8000/categories
content-type: application/json

{
    "name": "Эдийн засаг"
}

###
DELETE  http://localhost:8000/categories
###

PUT http://localhost:8000/categories
content-type: application/json
{
    "name": "Нийгэм"
}

###
GET http://localhost:8000/articles/bd356b2e-feba-47b6-86d5-de52d0980545

###
POST http://localhost:8000/articles

